"""SaktiOS UI — shell integration (Phase 6).

Generates the real system configuration that turns a stock install
into the SaktiOS fullscreen experience:

- wallpaper: swww (Hyprland) or feh (Openbox) pointing at
  ~/wallpapers/w1.png
- window manager: minimal Hyprland config (zero bars/panels, the UI
  started as exec-once) with an Openbox autostart fallback
- auto login: systemd getty override (tty1) + SDDM autologin snippet
- branding purge: ordered plan that removes Arch/Firefox/default-art
  traces (with package removal only when explicitly told)

Pure functions + tiny state so the same code is unit-tested on any
host and applied on the target via `sakti-ai ui install`.
"""

from __future__ import annotations

import os
import shutil
from dataclasses import dataclass, field
from typing import Dict, List, Optional

DEFAULT_HOME_WALLPAPER = "wallpapers/w1.png"
DEFAULT_HOME_LOGO = "assets/logo.png"

_DEFAULT_REMOVE = ("firefox", "firefox-i18n-*", "plasma-desktop",
                   "kde-gtk-config")


@dataclass
class ShellSetup:
    """Builds the OS-side files for the fullscreen SaktiOS experience."""

    home: str = ""
    wm: str = ""                    # "hyprland" | "openbox" | "" (auto)
    user: str = "sakti"
    ui_command: str = "sakti-ai ui serve"
    remove_apps: List[str] = field(
        default_factory=lambda: list(_DEFAULT_REMOVE))

    def __post_init__(self) -> None:
        self.home = self.home or os.path.expanduser("~")

    # ------------------------------------------------------- paths
    @property
    def wallpaper_path(self) -> str:
        return os.path.join(self.home, "wallpapers", "w1.png")

    @property
    def logo_path(self) -> str:
        return os.path.join(self.home, "assets", "logo.png")

    # -------------------------------------------------- wallpaper
    def wallpaper_command(self) -> Optional[str]:
        """Real wallpaper command for the detected WM (swww/feh)."""
        path = self.wallpaper_path
        if self.wm == "hyprland" or (not self.wm and shutil.which("swww")):
            return (f"swww img {path} --resize=crop "
                    f"# SaktiOS default wallpaper")
        if self.wm == "openbox" or (not self.wm and shutil.which("feh")):
            return f"feh --bg-fill {path}"
        return None

    # ------------------------------------------------- WM configs
    def hyprland_config(self) -> str:
        """Minimal Hyprland: no bars, no panels — the UI is the desktop."""
        wallpaper = self.wallpaper_command() or "# no wallpaper loader"
        return "\n".join([
            "# SaktiOS shell config — generated by `sakti-ai ui install`",
            "monitor = ,preferred,auto,1",
            f"exec-once = {self.ui_command}",
            f"exec-once = {wallpaper}",
            "",
            "general {",
            "    border_size = 1",
            "    col.active_border = rgba(34,211,238ee) "
            "rgba(129,140,248ee) rgba(192,132,252ee)",
            "    gaps_in = 6",
            "    gaps_out = 12",
            "}",
            "",
            "decoration {",
            "    rounding = 12",
            "    blur {",
            "        enabled = true",
            "        size = 4",
            "        passes = 2",
            "    }",
            "    drop_shadow = no",
            "}",
            "",
            "# light on resources (VirtualBox friendly)",
            "animations {",
            "    enabled = false",
            "}",
            "",
            "input {",
            "    kb_layout = us",
            "    follow_mouse = 1",
            "}",
            "",
            "misc { disable_hyprland_logo = true }",
        ])

    def openbox_autostart(self) -> str:
        """Openbox fallback: wallpaper + UI, nothing else runs."""
        lines = [
            "#!/usr/bin/env sh",
            f"# SaktiOS shell autostart — generated by "
            f"`sakti-ai ui install`",
            "",
            f"{self.wallpaper_command() or 'echo no wallpaper loader'}",
            "",
            f"{self.ui_command} &",
            "",
        ]
        return "\n".join(lines)

    # ----------------------------------------------- auto-login
    def getty_autologin(self) -> str:
        """systemd getty override that auto-logs in on tty1."""
        return "\n".join([
            "[Service]",
            "ExecStart=",
            f"ExecStart=-/usr/bin/agetty --autologin {self.user} "
            "--noclear tty1 linux",
            "",
        ])

    def sddm_autologin(self, session: str = "plasma") -> str:
        return "\n".join([
            "[Autologin]",
            f"Session={session}",
            f"User={self.user}",
            "",
        ])

    # ------------------------------------------- branding purge
    def purge_plan(self, with_packages: bool = True) -> List[str]:
        """Ordered human steps that strip non-SaktiOS traces.

        Package removal is opt-in (`with_packages`); the rest is file
        placement (wallpaper replacement, greeter theme, logo).
        """
        steps: List[str] = [
            f"install swww (Hyprland) or feh (Openbox) to load the "
            f"wallpaper",
            f"copy {self.wallpaper_path} over "
            "/usr/share/backgrounds/ (replace the default art)",
        ]
        if with_packages:
            steps.append(
                f"remove default applications: "
                f"{', '.join(self.remove_apps)} (pacman -Rns)")
        steps.extend([
            "remove /usr/share/backgrounds/archlinux/",
            "install the SaktiOS logo into /usr/share/pixmaps/ and "
            "set it as the greeter watermark",
            "set SDDM theme to 'sakti-login' and disable any other "
            "sessions in the greeter",
            "disable Waybar/Plasma panels so only the shell shows",
        ])
        return steps

    # --------------------------------------------------- generator
    def generate(self, out_dir: Optional[str] = None) -> List[str]:
        """Write every config into `out_dir` (default ~/.config/sakti).

        Pure file generation — no system changes — safe to run and
        test anywhere. Returns the absolute paths written.
        """
        base = os.path.abspath(out_dir or os.path.join(
            self.home, ".config", "sakti"))
        written: List[str] = []

        def write_rel(rel: str, content: str) -> None:
            path = os.path.join(base, rel)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
            written.append(path)

        if self.wm in ("hypr", "hyprland"):
            write_rel("hyprland/hyprland.conf", self.hyprland_config())
        else:
            write_rel("openbox/autostart", self.openbox_autostart())
        write_rel("systemd/system/getty@tty1.service.d/override.conf",
                  self.getty_autologin())
        write_rel("sddm.conf.d/autologin.conf",
                  self.sddm_autologin())
        return written

    # ----------------------------------------------------- status
    def status(self) -> Dict[str, object]:
        wm = self.wm or (
            "hyprland" if shutil.which("swww") else
            "openbox" if shutil.which("feh") else "unknown")
        return {
            "wm": wm,
            "wallpaper": self.wallpaper_path,
            "wallpaper_present": os.path.isfile(self.wallpaper_path),
            "logo": self.logo_path,
            "logo_present": os.path.isfile(self.logo_path),
            "ui_command": self.ui_command,
            "mode": "generate configs with `sakti-ai ui install`",
        }